"""Initial migration

Revision ID: 8c5d4ea27fe0
Revises: 
Create Date: 2024-01-28 21:44:35.274284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5d4ea27fe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_utilisateur', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mot_de_passe', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=300), nullable=False))
        batch_op.drop_constraint('users_mail_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['nom_utilisateur'])
        batch_op.drop_column('mail')
        batch_op.drop_column('nom')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mail', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_mail_key', ['mail'])
        batch_op.drop_column('email')
        batch_op.drop_column('mot_de_passe')
        batch_op.drop_column('nom_utilisateur')

    # ### end Alembic commands ###
